const listOfMovies = [
    {img: "https://upload.wikimedia.org/wikipedia/en/8/81/Poster-pursuithappyness.jpg",
    name: "Pursiut of happiness",
    year: "2006",
    star: 5,
    duration: "1h 57 minutes",
    id:1,
    category: "Drame"
    },
    {img: "https://m.media-amazon.com/images/M/MV5BYjQ5NjM0Y2YtNjZkNC00ZDhkLWJjMWItN2QyNzFkMDE3ZjAxXkEyXkFqcGdeQXVyODIxMzk5NjA@._V1_.jpg",
    name: "Coco",
    year: "2017",
    star: 3,
    duration: "1h 49 minutes",
    id:1,
    category: "Animation"
    },
    {img: "https://fr.web.img3.acsta.net/pictures/14/04/03/12/56/160545.jpg",
    name: "Maléfique",
    year: "2014",
    star: 5,
    duration: "1h 37 minutes",
    id:1,
    category: "Thriller"
    },
    {img: "https://vincentvietnamblog.files.wordpress.com/2017/05/1-me-before-you.jpg?w=1108",
    name: "Me before you",
    year: "2016",
    star: 5,
    duration: "1h 51 minutes",
    id:1,
    category: "Romance"
    },
    {img: "https://cdn1.webmanagercenter.com/tekiano/wp-content/uploads/2019/01/dachra-affiche-1.jpg",
    name: "Dachra",
    year: "2018",
    star: 5,
    duration: "1h 54 minutes",
    id:1,
    category: "Horreur"
    },

    {img: "https://images-na.ssl-images-amazon.com/images/I/51TfUWh5N9L._AC_SY445_.jpg",
    name: "Inception",
    year: "2010",
    star: 3,
    duration: "2h 28 minutes",
    id:2,
    category: "science-fiction"},

    {img: "https://i.pinimg.com/originals/aa/c5/68/aac5685ae1204004d4125891dd8a9726.jpg",
    name: "3 metros sobre el cielo",
    year: "2010",
    star: 4,
    duration: "2h 03 minutes",
    id:3,
    category: "Romance"},

    {img: "https://i.pinimg.com/originals/fb/c6/d7/fbc6d73bc1d80a347c057656ff9f7b36.jpg",
    name: "a walk to remember",
    year: "2002",
    star: 5,
    duration: "1h 42 minutes",
    id:4,
    category: "Romance"},

    {img: "https://images-na.ssl-images-amazon.com/images/I/A1tC7-MIB2L._AC_SY445_.jpg",
    name: "Colonia",
    year: "2015",
    star: 1,
    duration: "1h 50 minutes",
    id:5,
    category: "thriller"},

    {img: "https://imgr.cineserie.com/2018/07/707202.jpg?imgeng=/f_jpg/cmpr_0/w_208/h_320/m_cropbox&ver=1",
    name: "La fureur du Dragon:Bruce Lee",
    year: "1972",
    star: 2,
    duration: "2h 13 minutes",
    id:6,
    category: "Action"}
]

export default listOfMovies